movingdrawable:
	javac -d . Drawable.java MovingDrawable.java GUIRobot.java Coordinate.java
	java factory.agentGUI.MovingDrawable > movingdrawable.txt

manager:
	javac -d . Manager.java ManagerConnection.java