BASE=Drawable.java MovingDrawable.java Coordinate.java
PARAM=-d .

movingdrawable:
	javac $(PARAM) $(BASE) 
	java factory.agentGUI.MovingDrawable > _movingdrawable.txt
kitrobot:
	javac $(PARAM) $(BASE) GUIRobot.java 

